{
 "title": "GO.Charity Auth microservice dashboard",
 "tags": [ "go.charity" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "GO.Charity Auth microservice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Averge memory used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(goa_nodejs_memory_usage_bytes / 1024 / 2024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th Response Time",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_request_duration_milliseconds_bucket[1m])) by (le, path, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success rates: Requests with 200 - 300 status codes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(increase(api_request_duration_milliseconds_count{code=~\"^2..$\"}[1m]))\r\n/\r\nsum(increase(api_request_duration_milliseconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate: Requests with 5xx status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(api_request_duration_milliseconds_count{code=~\"^5..$\"}[1m]))\r\n/\r\nsum(increase(api_request_duration_milliseconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median response time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(api_request_duration_milliseconds_bucket[1m])) by (le, path, method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(api_request_duration_milliseconds_count[1m])) by (service, route, method, code)  * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "avg(rate(api_request_duration_milliseconds_sum[1m]) / rate(api_request_duration_milliseconds_count[1m])) by (path, method, code)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}