"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const dotenv_1 = require("dotenv");
const cors_1 = __importDefault(require("cors"));
const db_config_1 = __importDefault(require("./models/db.config"));
const login_1 = __importDefault(require("./routes/login"));
const register_1 = __importDefault(require("./routes/register"));
const refresh_token_1 = __importDefault(require("./routes/refresh_token"));
const body_parser_1 = __importDefault(require("body-parser"));
(0, dotenv_1.config)();
(0, db_config_1.default)();
const app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(body_parser_1.default.json());
app.use(body_parser_1.default.urlencoded({ extended: true }));
app.use("/v1/login", login_1.default);
app.use("/v1/register", register_1.default);
app.use("/v1/refresh_token", refresh_token_1.default);
exports.default = app;
